### PR TITLE
fix for custom user-emacs-directory

### PR DESCRIPTION
**Pull request by acml**
I have  cloned doom emacs to ~/.emacs.d.doom.

In order to use spacemacs module for doom with my customized installation of doom emacs these changes were necessary.

Instructions for loading the module had to change as well:

Load the module in config.el
(load! (concat user-emacs-directory "modules/spacemacs/+spacemacs"))

### CODE REVIEW

**Comment by chenyanming** [comment]
Thanks for your feedback. Since some users already clone the module to
`~/.doom/modules/spacemacs`, therefore, changing it to `user-emacs-directory` is
inappropriate. However, based on your request, I made a workaround:

1. Set `spacemacs-path` to `doom-modules-dir`, before you load `+spacemacs.el`
`(setq spacemacs-path doom-modules-dir)`

2. Then load `+spacmeacs.el` in `config.el`
`(load! (concat spacemacs-path "spacemacs/+spacemacs"))
`

It should be more flexible.

**Comment by acml** [comment]
Thanks. It is all good now.

**Comment by chenyanming** [comment]
Ok. This pull is considered closed.

**Comment by chenyanming** [comment]
The new version can be cloned to any directories you like and no need to setq `spacemace-path`. Since I use `load-file-name` to determine the module path, which is more approriate.

**Pull request closed without merging**
